# Generated by Django 3.2.3 on 2021-06-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_delete_result'),
        ('konto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='test_title',
        ),
        migrations.AddField(
            model_name='result',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.test'),
            preserve_default=False,
        ),
    ]
