# Generated by Django 3.2.3 on 2021-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0006_auto_20210614_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='max_score',
        ),
        migrations.AlterField(
            model_name='result',
            name='completion_date',
            field=models.DateTimeField(verbose_name='completion'),
        ),
    ]
