# Generated by Django 3.2.3 on 2021-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
