# Generated by Django 3.2.3 on 2021-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateField(verbose_name='published'),
        ),
    ]
